- name: Create vault user group
  group: 
    name: "{{ vault_group }}"

- name: Create vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present

- name: Install prerequisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ vault_install_prerequisites }}"

- name: Download Hashicorp Vault binary
  get_url:
    url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
    dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
    checksum: "{{ vault_checksum }}"
  register: vault_download

- name: Unzip vault archive
  unarchive:
    src: "{{ vault_download.dest }}"
    dest: /usr/local/bin
    copy: no
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755

- name: Copy systemd file
  template:
    src: vault.service
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root

- name: Create dir for vault.hcl config
  file:
    path: "{{ vault_config_dir }}"
    state: directory

- name: Create Vault config file
  template:
    src: vault.hcl
    dest: "{{ vault_config_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Create storage dir
  file:
    path: "{{ vault_storage_dir }}"
    state: directory
    mode: 0700
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Start and enable vault service
  service:
    name: vault
    state: started
    enabled: yes

