- name: Read unseal key contents
  command: cat {{item}}
  register: unseal_keys
  with_fileglob: "{{ unseal_keys_dir }}/*"
  delegate_to: localhost
  become: no

- name: Unseal vault with unseal keys
  shell: |
    /usr/local/bin/vault operator unseal {{ item.stdout }}
  environment:
    VAULT_ADDR: "http://{{ hostvars['vault_node'].ansible_host }}:8200"
  with_items: "{{ unseal_keys.results }}"

- debug:
    var: vault_init_parsed.root_token
